# https://medium.com/analytics-vidhya/getting-started-with-postgresql-using-docker-compose-34d6b808c47c
version: '3.1'

services:
  db:
    image: postgres
    container_name: database
    restart: always
    env_file:
      - database.env
    ports:
      - '5432:5432'
    volumes:
      - ./database:/var/lib/postgresql/data/

  app:
    image: python:latest
    container_name: app
    volumes:
      - ./app:/home/root/app
    working_dir: /home/root/app

